nama = input("Nama\t\t\t:")
nim = input("NIM\t\t\t:")
kp = input("Kelas Paralel\t\t:")
ttl = input("Tempat/Tanggal Lahir\t:")
a = input("Alamat\t\t\t:")
h = input("Hobby\t\t\t:")
hp = input("No. HP\t\t\t:")
print("Ouput:")
print("Nama\t\t\t: " + nama)
print("NIM\t\t\t: " + nim)
print("Kelas Paralel\t\t: " + kp)
print("Tempat/Tanggal Lahir\t: " + ttl)
print("Alamat\t\t\t: " + a)
print("Hobby\t\t\t: " + h)
print("No. HP\t\t\t: " + hp)